name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    #node version
    
    strategy:
      matrix:
        node-version: [^14.17.0 || ^16.13.0 || >=18.0.0]
    
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ matrix.node-version }}
    
    - uses: actions/checkout@v2
      
    - run: npm init -y
    - run: npm i -g npm@latest
    - run: npm install
    
    - run: npm run cy:run
      continue-on-error: true
    
    - run: npm run report:merge
    
    - run: npm run report:mocha
    
    - name: Deploy to Github
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: mochawesome-report
